# Generated by Django 5.1.6 on 2025-03-02 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_tasa', models.FloatField()),
                ('tipo_tasa', models.CharField(choices=[('Efectiva', 'Efectiva'), ('Nominal', 'Nominal')], max_length=10)),
                ('plazo_tasa', models.IntegerField()),
                ('capitalizacion', models.FloatField()),
            ],
            options={
                'verbose_name': 'Tasa',
                'verbose_name_plural': 'Tasas',
            },
        ),
        migrations.CreateModel(
            name='CarteraDescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_descuento', models.DateField()),
                ('tcea_calculada', models.FloatField(blank=True, null=True)),
                ('unidad_monetaria', models.CharField(choices=[('USD', 'Dólares'), ('PEN', 'Soles')], max_length=3)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tasa')),
            ],
            options={
                'verbose_name': 'Cartera de Descuento',
                'verbose_name_plural': 'Carteras de Descuento',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_factura', models.FloatField()),
                ('cliente', models.CharField(max_length=255)),
                ('fecha_emision', models.DateField()),
                ('fecha_pago', models.DateField()),
                ('unidad_monetaria', models.CharField(choices=[('USD', 'Dólares'), ('PEN', 'Soles')], max_length=3)),
                ('estado_pago', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=10)),
                ('cartera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.carteradescuento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
            },
        ),
        migrations.CreateModel(
            name='Letra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_nominal', models.FloatField()),
                ('beneficiario', models.CharField(max_length=100)),
                ('fecha_giro', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('unidad_monetaria', models.CharField(choices=[('USD', 'Dólares'), ('PEN', 'Soles')], max_length=3)),
                ('estado_pago', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=10)),
                ('cartera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.carteradescuento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Letra',
                'verbose_name_plural': 'Letras',
            },
        ),
    ]
