# Generated by Django 5.1.6 on 2025-03-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carteradescuento',
            name='tasa',
        ),
        migrations.RemoveField(
            model_name='carteradescuento',
            name='fecha_descuento',
        ),
        migrations.RemoveField(
            model_name='carteradescuento',
            name='unidad_monetaria',
        ),
        migrations.AddField(
            model_name='carteradescuento',
            name='capitalizacion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carteradescuento',
            name='tipo_tasa',
            field=models.CharField(choices=[('Efectiva', 'Efectiva'), ('Nominal', 'Nominal')], default='Efectiva', max_length=10),
        ),
        migrations.AddField(
            model_name='carteradescuento',
            name='valor_tasa',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='factura',
            name='unidad_monetaria',
            field=models.CharField(choices=[('USD', 'Dólares'), ('PEN', 'Soles')], default='PEN', max_length=3),
        ),
        migrations.AlterField(
            model_name='letra',
            name='unidad_monetaria',
            field=models.CharField(choices=[('USD', 'Dólares'), ('PEN', 'Soles')], default='PEN', max_length=3),
        ),
        migrations.DeleteModel(
            name='Tasa',
        ),
    ]
