# Generated by Django 5.1.6 on 2025-03-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_carteradescuento_tasa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carteradescuento',
            name='nombre',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
