# Generated by Django 5.1.6 on 2025-03-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_carteradescuento_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carteradescuento',
            name='valor_tasa',
            field=models.FloatField(null=True),
        ),
    ]
