# Generated by Django 5.1.6 on 2025-03-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_carteradescuento_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carteradescuento',
            name='tcea_calculada',
        ),
        migrations.AlterField(
            model_name='carteradescuento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
